### ISSUE TITLE
TEI Boilerplate not rendering with teibp.xsl

### ISSUE THREAD

**Issue by melaniewalsh** [TEI-Boilerplate/TEI-Boilerplate#31]
Thank you for TEI boilerplate!

We are having trouble getting TEI boilerplate to render correctly on our GitHub pages site, and I was wondering if you all had any suggestions.

We've cloned the TEI Boilerplate GitHub repo exactly (https://github.com/huck1989/TEI-Boilerplate-test), and the XML files (https://github.com/huck1989/TEI-Boilerplate-test/blob/main/src/content/hardy_a_singer_asleep.xml), which link to "teibp.xsl", are still not rendering correctly: https://huck1989.github.io/TEI-Boilerplate-test/src/content/hardy_a_singer_asleep.xml

 <img width="1033" alt="Screenshot 2023-12-11 at 4 42 42 PM" src="https://github.com/TEI-Boilerplate/TEI-Boilerplate/assets/20325102/dff68340-94ac-4e30-a5f6-a36a36a78f2d">

Do you have any suggestions about what might be going wrong or how to address this issue? Thank you!

**Comment by melaniewalsh** [comment]
Update: I think the issue is that the teibp.xsl was linking to a teibp.less file that no longer exists, and that the wrong line was commented out: https://github.com/TEI-Boilerplate/TEI-Boilerplate/blob/b306168588177b2b5e1bad27c91013d2754eac9c/src/content/teibp.xsl#L305

I made a pull request to fix this issue in #32

**Comment by GrantLS** [comment]
Thanks, @melaniewalsh. I have pulled in your fix and have released version 1.2.1.
